package quanlyks.views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Desktop;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.write.WriteException;
import quanlyks.controller.CustomerController;
import quanlyks.controller.ExportFile;
import quanlyks.controller.IconManager;
import quanlyks.model.Customer;

/**
 *
 * @author Tuyen Ti Ton
 */
public class CustomerPanel extends javax.swing.JPanel {

    /**
     * Creates new form StaffPanel
     */
    public static CustomerController customerController = new CustomerController();
    ArrayList<Customer> arrCustomers = new ArrayList<>();
    private IconManager icon = new IconManager();
    private boolean checkSearch = false;

    public CustomerPanel() {
        initComponents();
        arrCustomers = customerController.getListCustomer();
        bindingTableCustomer(arrCustomers);
        analysisCustomer();
        if (MainScreen.type == 2) {
            btnDelete.setEnabled(false);
        }
        TSearch.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                int key = e.getKeyCode();
                if (key == KeyEvent.VK_ENTER) {
                    querySearch();
                }
            }
        });
    }

    public static void bindingTableCustomer(ArrayList<Customer> arrCustomer) {
        DefaultTableModel model = (DefaultTableModel) tbCustomer.getModel();
        model.setRowCount(0);
        for (int i = 0; i < arrCustomer.size(); i++) {
            model.addRow(new Object[]{
                arrCustomer.get(i).getIdCustomer(),
                arrCustomer.get(i).getNameCustomer(),
                arrCustomer.get(i).getSex(),
                arrCustomer.get(i).getPhoneNumber(),
                arrCustomer.get(i).getNational(),});
        }
        tbCustomer.setModel(model);
    }

    public static void analysisCustomer() {
        StringBuilder builer = new StringBuilder();
        builer.append("Thống kê khách hàng\n");
        ArrayList<String> arrNational = customerController.getListNational();
        for (int i = 0; i < arrNational.size(); i++) {
            builer.append(arrNational.get(i) + ": ");
            int number = customerController.countCustomerByNational(arrNational.get(i));
            builer.append(number + "\n");
        }
        taAnalysis.setText(builer.toString());
    }

    public void querySearch() {
        String query = TSearch.getText();
        arrCustomers = customerController.searchCustomer(query);
        if (arrCustomers.size() != 0) {
            bindingTableCustomer(arrCustomers);
            iconSearch.setIcon(icon.iconBack());
            checkSearch = true;
        } else {
            JOptionPane.showMessageDialog(this, "Không có kết quả phù hợp", "Tìm kiếm", JOptionPane.INFORMATION_MESSAGE, icon.iconError());
            iconSearch.setIcon(icon.iconSearch());
            checkSearch = false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbCustomer = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAnalysis = new javax.swing.JTextArea();
        btnView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TSearch = new javax.swing.JTextField();
        iconSearch = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1022, 525));

        tbCustomer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Họ và tên", "Giới tính", "Số điện thoại", "Quốc tịch"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCustomer.setRowHeight(25);
        tbCustomer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCustomer);
        if (tbCustomer.getColumnModel().getColumnCount() > 0) {
            tbCustomer.getColumnModel().getColumn(0).setResizable(false);
            tbCustomer.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbCustomer.getColumnModel().getColumn(1).setResizable(false);
            tbCustomer.getColumnModel().getColumn(1).setPreferredWidth(150);
            tbCustomer.getColumnModel().getColumn(2).setResizable(false);
            tbCustomer.getColumnModel().getColumn(2).setPreferredWidth(10);
            tbCustomer.getColumnModel().getColumn(3).setResizable(false);
            tbCustomer.getColumnModel().getColumn(4).setResizable(false);
            tbCustomer.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        btnEdit.setBackground(new java.awt.Color(0, 153, 255));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyks/images/edit_white.png"))); // NOI18N
        btnEdit.setText("Chỉnh sửa");
        btnEdit.setToolTipText("");
        btnEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEdit.setIconTextGap(15);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(0, 153, 255));
        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyks/images/printer_white.png"))); // NOI18N
        btnPrint.setText("In danh sách");
        btnPrint.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrint.setIconTextGap(15);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        taAnalysis.setEditable(false);
        taAnalysis.setColumns(20);
        taAnalysis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taAnalysis.setLineWrap(true);
        taAnalysis.setRows(5);
        taAnalysis.setAutoscrolls(false);
        jScrollPane2.setViewportView(taAnalysis);

        btnView.setBackground(new java.awt.Color(0, 153, 255));
        btnView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyks/images/view_white.png"))); // NOI18N
        btnView.setText("Xem chi tiết");
        btnView.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnView.setIconTextGap(15);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Tìm kiếm");

        TSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSearchActionPerformed(evt);
            }
        });

        iconSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyks/images/search_black.png"))); // NOI18N
        iconSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconSearchMouseClicked(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 153, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyks/images/delete_white.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setToolTipText("");
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDelete.setIconTextGap(15);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnHistory.setBackground(new java.awt.Color(0, 153, 255));
        btnHistory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyks/images/history_white.png"))); // NOI18N
        btnHistory.setText("Lịch sử đặt phòng");
        btnHistory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHistory.setIconTextGap(15);
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconSearch)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCustomerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCustomerMouseClicked

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        int row = tbCustomer.getSelectedRow();
        if (row != -1) {
            Customer customer = arrCustomers.get(row);
            try {
                CustomerInfo cusInfo = new CustomerInfo(this, customer, 1);
                cusInfo.setVisible(true);
                cusInfo.setLocationRelativeTo(null);
                cusInfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            } catch (ParseException ex) {
                Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Chưa chọn mục nào!", "Trống", JOptionPane.ERROR_MESSAGE, icon.iconError());
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = tbCustomer.getSelectedRow();
        if (row != -1) {
            Customer customer = arrCustomers.get(row);
            CustomerInfo ctmInfo;
            try {
                ctmInfo = new CustomerInfo(this, customer, 2);
                ctmInfo.setVisible(true);
                ctmInfo.setLocationRelativeTo(null);
                ctmInfo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            } catch (ParseException ex) {
                Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa chọn mục nào!", "Trống", JOptionPane.ERROR_MESSAGE, icon.iconError());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            ExportFile exp = new ExportFile();
            File file = new File("Xls\\" + MainScreen.getCurrentDateTime() + ".xls");
            exp.printTable(tbCustomer, file);
            int output = JOptionPane.showConfirmDialog(this, "Mở danh sách", "Danh sách", JOptionPane.YES_NO_OPTION);
            if (output == JOptionPane.YES_OPTION) {
                try {
                    Desktop.getDesktop().open(file);
                } catch (IOException ex) {
                    Logger.getLogger(RoomPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (WriteException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void iconSearchMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if (checkSearch == false) {
            querySearch();
        } else {
            arrCustomers = customerController.getListCustomer();
            bindingTableCustomer(arrCustomers);
            iconSearch.setIcon(icon.iconSearch());
            checkSearch = false;
        }

    }
    private void TSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tbCustomer.getSelectedRow();
        if (row != -1) {
            String idCus = tbCustomer.getValueAt(row, 0).toString();
            int output = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa khách hàng " + idCus + "?", "Xóa khách hàng", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon.iconDelete());
            if (output == JOptionPane.YES_OPTION) {
                if (customerController.deleteCustomer(idCus)) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công", "Xóa", JOptionPane.INFORMATION_MESSAGE, icon.iconDone());
                    bindingTableCustomer(customerController.getListCustomer());
                    analysisCustomer();
                } else {
                    JOptionPane.showMessageDialog(this, "Chưa xóa được", "Lỗi", JOptionPane.ERROR_MESSAGE, icon.iconError());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa chọn mục nào!", "Trống", JOptionPane.ERROR_MESSAGE, icon.iconError());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        int row = tbCustomer.getSelectedRow();
        if (row != -1) {
            String idCustomer = tbCustomer.getValueAt(row, 0).toString();
            String nameCustomer = tbCustomer.getValueAt(row, 1).toString();
            HistoryOder history = new HistoryOder(idCustomer, nameCustomer);
            history.setVisible(true);
            history.pack();
            history.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            history.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Chưa chọn mục nào!", "Trống", JOptionPane.ERROR_MESSAGE, icon.iconError());
        }
    }//GEN-LAST:event_btnHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TSearch;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel iconSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea taAnalysis;
    public static javax.swing.JTable tbCustomer;
    // End of variables declaration//GEN-END:variables
}
