package quanlyks.views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Desktop;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.write.WriteException;
import quanlyks.controller.ExportFile;
import quanlyks.controller.IconManager;
import quanlyks.controller.StaffController;
import quanlyks.model.Staff;

/**
 *
 * @author Tuyen Ti Ton
 */
public class StaffPanel extends javax.swing.JPanel {

    /**
     * Creates new form StaffPanel
     */
    private ArrayList<Staff> listStaff = new ArrayList<>();
    public static StaffController staffController;
    private IconManager icon = new IconManager();
    private boolean checkSearch = false;
    ExportFile file = new ExportFile();

    /**
     * Creates new form StaffPanel
     */
    public StaffPanel() {
        initComponents();
        staffController = new StaffController();
        listStaff = staffController.getListStaff();
        loadTableStaff(listStaff);
        analysiStaff();
        if (MainScreen.type == 2) {
            btnAdd.setEnabled(false);
            btnDelete.setEnabled(false);
            btnEdit.setEnabled(false);
        }
        edtSearch.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                int keyEvent = e.getKeyCode();
                if (keyEvent == KeyEvent.VK_ENTER) {
                    // thực hiện hàm tìm kiếm
                    String key = edtSearch.getText();
                    searchStaff(key);
                }
            }

        });
    }

    public static void analysiStaff() {
        StringBuilder builder = new StringBuilder();
        builder.append("Thống kê nhân viên\n");
        ArrayList<String> arrOffice = staffController.getListOffice();
        for (int i = 0; i < arrOffice.size(); i++) {
            builder.append(arrOffice.get(i) + ": ");
            builder.append(staffController.getNumberStaffByOffice(arrOffice.get(i)) + "\n");
        }
        taAnalysis.setText(builder.toString());
    }

    public void loadTableStaff(ArrayList<Staff> listStaff) {
        DefaultTableModel model = (DefaultTableModel) tbStaff.getModel();
        model.setRowCount(0);
        for (int i = 0; i < listStaff.size(); i++) {
            model.addRow(new Object[]{
                listStaff.get(i).getIdStaff(),
                listStaff.get(i).getNameStaff(),
                listStaff.get(i).getSex(),
                listStaff.get(i).getPhoneNumber(),
                listStaff.get(i).getOffice()
            });
        }
        tbStaff.setModel(model);
    }

    private void searchStaff(String key) {
        listStaff = staffController.searchRoom(key);
        if (listStaff.size() != 0) {
            loadTableStaff(listStaff);
            btnSearch.setIcon(icon.iconBack());
            checkSearch = true;
        } else {
            JOptionPane.showMessageDialog(this, "Không có kết quả phù hợp", "Tìm kiếm", JOptionPane.INFORMATION_MESSAGE, icon.iconError());
            btnSearch.setIcon(icon.iconSearch());
            checkSearch = false;
        }
    }

    private void analysisStaff() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbStaff = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAnalysis = new javax.swing.JTextArea();
        btnView = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        edtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1022, 525));

        tbStaff.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbStaff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Họ và tên", "Giới tính", "Số điện thoại", "Chức vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbStaff.setRowHeight(25);
        tbStaff.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbStaff);
        if (tbStaff.getColumnModel().getColumnCount() > 0) {
            tbStaff.getColumnModel().getColumn(0).setResizable(false);
            tbStaff.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbStaff.getColumnModel().getColumn(1).setResizable(false);
            tbStaff.getColumnModel().getColumn(1).setPreferredWidth(150);
            tbStaff.getColumnModel().getColumn(2).setResizable(false);
            tbStaff.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbStaff.getColumnModel().getColumn(3).setResizable(false);
            tbStaff.getColumnModel().getColumn(4).setResizable(false);
        }

        btnAdd.setBackground(new java.awt.Color(0, 153, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyks/images/add_white.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdd.setIconTextGap(15);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 153, 255));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyks/images/edit_white.png"))); // NOI18N
        btnEdit.setText("Chỉnh sửa");
        btnEdit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEdit.setIconTextGap(15);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 153, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyks/images/delete_white.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDelete.setIconTextGap(15);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(0, 153, 255));
        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyks/images/printer_white.png"))); // NOI18N
        btnPrint.setText("In danh sách");
        btnPrint.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrint.setIconTextGap(15);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        taAnalysis.setEditable(false);
        taAnalysis.setColumns(20);
        taAnalysis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        taAnalysis.setLineWrap(true);
        taAnalysis.setRows(5);
        taAnalysis.setAutoscrolls(false);
        jScrollPane2.setViewportView(taAnalysis);

        btnView.setBackground(new java.awt.Color(0, 153, 255));
        btnView.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyks/images/view_white.png"))); // NOI18N
        btnView.setText("Xem chi tiết");
        btnView.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnView.setIconTextGap(15);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Tìm kiếm");

        edtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyks/images/search_black.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStaffMouseClicked

    }//GEN-LAST:event_tbStaffMouseClicked

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int row = tbStaff.getSelectedRow();
        if (row != -1) {
            try {
                Staff staff = new Staff();
                if (checkSearch == true) {
                    staff = listStaff.get(row);
                } else {
                    listStaff = staffController.getListStaff();
                    staff = listStaff.get(row);
                }
                StaffInfor staffInfor = new StaffInfor(this, staff, 1);
                staffInfor.setVisible(true);
                staffInfor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                staffInfor.setLocationRelativeTo(null);
            } catch (ParseException ex) {
                Logger.getLogger(StaffPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa chọn mục nào!", "Trống", JOptionPane.ERROR_MESSAGE, icon.iconError());
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        String key = edtSearch.getText();
        if (checkSearch == false) {
            searchStaff(key);
        } else {
            listStaff = staffController.getListStaff();
            loadTableStaff(listStaff);
            btnSearch.setIcon(icon.iconSearch());
            checkSearch = false;
        }
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            StaffInfor staffInfor = new StaffInfor(this, null, 3);
            staffInfor.setVisible(true);
            staffInfor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            staffInfor.setLocationRelativeTo(null);
        } catch (ParseException ex) {
            Logger.getLogger(StaffPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = tbStaff.getSelectedRow();
        if (row != -1) {
            try {
                Staff staff = new Staff();
                if (checkSearch == true) {
                    staff = listStaff.get(row);
                } else {
                    listStaff = staffController.getListStaff();
                    staff = listStaff.get(row);
                }
                StaffInfor staffInfor = new StaffInfor(this, staff, 2);
                staffInfor.setVisible(true);
                staffInfor.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                staffInfor.setLocationRelativeTo(null);
            } catch (ParseException ex) {
                Logger.getLogger(StaffPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa chọn mục nào!", "Trống", JOptionPane.ERROR_MESSAGE, icon.iconError());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int i = tbStaff.getSelectedRow();
        if (i != -1) {
            String idStaff = tbStaff.getValueAt(i, 0).toString();
            int output = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa nhân viên " + idStaff + "?", "Xóa nhân viên", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon.iconDelete());
            if (output == JOptionPane.YES_OPTION) {
                if (staffController.deleteStaff(idStaff)) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công", "Xóa", JOptionPane.INFORMATION_MESSAGE, icon.iconDone());
                    loadTableStaff(listStaff);
                    analysiStaff();
                } else {
                    JOptionPane.showMessageDialog(this, "Chưa xóa được", "Lỗi", JOptionPane.ERROR_MESSAGE, icon.iconError());
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Chưa chọn mục nào!", "Trống", JOptionPane.ERROR_MESSAGE, icon.iconError());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            ExportFile exp = new ExportFile();
            File file = new File("Xls\\" + MainScreen.getCurrentDateTime() + ".xls");
            exp.printTable(tbStaff, file);
            int output = JOptionPane.showConfirmDialog(this, "Mở danh sách", "Danh sách", JOptionPane.YES_NO_OPTION);
            if (output == JOptionPane.YES_OPTION) {
                try {
                    Desktop.getDesktop().open(file);
                } catch (IOException ex) {
                    Logger.getLogger(RoomPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (WriteException ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField edtSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea taAnalysis;
    private javax.swing.JTable tbStaff;
    // End of variables declaration//GEN-END:variables
}
